### PR TITLE
Adding ContactUs Page

### LINKED ISSUE #99: Feat: Contact Us page
# 🚀 QuizQuest Issue Tracker

### 🌟 Feature Request

**Title**: Contact Us form

**Description**:
- **Overview**: I want to implement a contact us form by which user can be interact with you if someone have any query then it will send a brief description with their email and name.
- **Benefits**: It increases the user interaction towards application like if someone have doubt they can send you mail.
- **Possible Implementation**: We will create a contact us form and also have form some feature on it:)

https://github.com/user-attachments/assets/4efe35ff-0c6e-45ea-b2d3-e877dcbcb340

Something similar to this:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #99 Adding ContactUs form to the website:)

https://github.com/user-attachments/assets/1c00d40c-403b-4df1-87f6-50ce6da1f80e

@BhattAnsh Please review and merge it:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@BhattAnsh Please assign **level-3** because of interactive **ContactUs page**:)

**Comment by BhattAnsh** [comment]
raise the pr in development branch brother

**Comment by harshbhar0629** [comment]
@BhattAnsh Please review base branch changes main->development:)

**Comment by harshbhar0629** [comment]
@Wahid7852 Please don't remove level-3 you can see code changes it required alot of time to implement and alot of lines of codes not a 10-20 lines of codes.

**Comment by harshbhar0629** [comment]
@BhattAnsh please don't remove level-3 it requires alot of time and you can see the changes file

**Pull request merged**
