### PR TITLE
Bug: Contact Link Updated

### LINKED ISSUE #143: BUG: ContactUs Page Link not working
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: In footer when we click on contact us link then it navigates to not found page but contactUs page exist.

**Description**:
- **Steps to Reproduce**:
  1. We have to update the path of contact us.

- **Expected Result**: When we click on contactUs page then it navigates to contact us page.
- **Actual Result**: There is no behaviour at all to navigates to contactUs page it navigates to not found page.
- **Screenshots**: 

https://github.com/user-attachments/assets/86e39760-d9e6-46b2-bb84-3f8230a4c97d

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #143 Update contact Link .

https://github.com/user-attachments/assets/20b49df9-8257-4e4e-a5fc-99063bd8f1e9

@BhattAnsh Please review it and merge it with labels:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20  @techy4shri Please review it and merge it:)

**Comment by harshbhar0629** [comment]
@techy4shri Why you don't merge it.??

**Comment by techy4shri** [comment]
@harshbhar0629 because we need approval from the PA. So you need to wait.

**Comment by ShashwatAgrawal20** [comment]
hey @harshbhar0629 this looks good but you still need to update the link in the footer please do that. [here](https://github.com/BhattAnsh/Quiz-Quest/blob/development/QuizQuestFrontend/src/components/Footer.jsx#L99)

and can you also fix this too, it's just a small link change. 
image

CC: @BhattAnsh @Wahid7852 @techy4shri

**Comment by harshbhar0629** [comment]
Ok sure

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20 @BhattAnsh @techy4shri @Wahid7852 Please review and merge it tomorrow will be last day:)

**Comment by ShashwatAgrawal20** [comment]
Don't worry will do

**Review by techy4shri — APPROVED** [review]
LGTM! @ShashwatAgrawal20 Except I cannot see the explore button link.

**Comment by ShashwatAgrawal20** [comment]
> LGTM! @ShashwatAgrawal20 Except I cannot see the explore button link.

@harshbhar0629 please fix the Explore button too, it's just a single line change.

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20 What do you want from explore btn when we click on explore it render /explore ... Do you want to render about us page.?

**Comment by ShashwatAgrawal20** [comment]
> @ShashwatAgrawal20 What do you want from explore btn when we click on explore it render /explore ... Do you want to render about us page.?

https://github.com/BhattAnsh/Quiz-Quest/blob/development/QuizQuestFrontend/src/components/navbar.jsx#L74-L78

see this, you just need to add that onclick navigate thing to explore just like login.

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20 see now:)

**Review by techy4shri — COMMENTED** [review]
@BhattAnsh Please check, looks good.

**Review by ShashwatAgrawal20 — APPROVED** [review]
LGTM! 

shipit

**Review by techy4shri — APPROVED** [review]
Looks good to me, I approve!

**Pull request merged**
