### PR TITLE
Icon correction

### LINKED ISSUE #155: Duplicate icon is shown in mobile view in navbar
# 🚀 QuizQuest Issue Tracker

### 🌟 Feature Request

**Title**: [ Add a new icon and remove duplicate in navbar as shown in mobile view]

**Description**:
- **Overview**: There is duplicate search icon and contact icon is there .
- **Benefits**: By chaning duplicate icon and adding correct icon we get clear view what is is the use of the icon in navbar .
  
**Screenshot **:
Screenshot 2024-11-06 at 2 47 17 PM

@BhattAnsh, please assign me this task to fix this issue with labels.

### PR DESCRIPTION
**Pull request by niteshkr100**
## Description
I have remove the duplicate Icon of search in navbar and add a correct Icon for contact Icon.
Fixes #155 

## Screenshot of Correct of Icon 
Screenshot 2024-11-07 at 10 04 11 PM
 

@BhattAnsh , please merged my work with gssoc-ext & hacktoberfest level.

### CODE REVIEW

**Comment by BhattAnsh** [comment]
correct the whole nav bar

**Comment by niteshkr100** [comment]
> correct the whole nav bar

**Comment by niteshkr100** [comment]
> correct the whole nav bar

what changes or correction do you want. Please  explain me more about this.

**Comment by BhattAnsh** [comment]
you've only fixed the icons but the whole navbar is still not responsive make it responsive and send me the working video or image

**Comment by BhattAnsh** [comment]
and resolve conflicts in your code

**Comment by niteshkr100** [comment]
> you've only fixed the icons but the whole navbar is still not responsive make it responsive and send me the working video or image

Screenshot 2024-11-10 at 12 57 01 PM

This is looking good? can I pr now

**Comment by BhattAnsh** [comment]
no still there is issue the icon circle ideally should be in the center you have to reduce its size and then resolve teh conflicts there is still few conflicts in you code

**Comment by niteshkr100** [comment]
> no still there is issue the icon circle ideally should be in the center you have to reduce its size and then resolve teh conflicts there is still few conflicts in you code

#screenshot
Screenshot 2024-11-10 at 2 14 27 PM

please give me review for pull request

**Comment by niteshkr100** [comment]
> no still there is issue the icon circle ideally should be in the center you have to reduce its size and then resolve teh conflicts there is still few conflicts in you code

I am unable to understand the conflict can please help me in resolving this conflict issue.

**Comment by techy4shri** [comment]
@niteshkr100 go to the option right below your comment where it says to resolve conflicts and resolve them.

**Comment by niteshkr100** [comment]
> @niteshkr100 go to the option right below your comment where it says to resolve conflicts and resolve them.

Thank you for your help.

**Comment by niteshkr100** [comment]
@BhattAnsh, please help me to complete my pull request for merge.

**Comment by techy4shri** [comment]
@BhattAnsh dekh lo, bas hardcoded secret hai, but should be fine.

**Pull request merged**
