### PR TITLE
Feat: Adding Signup page

### LINKED ISSUE #60: Create Signup Profile Creation Page
Redesign the signup page to integrate beautiful profile creation

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #60  Adding signup page and also notified after creating an account!

https://github.com/user-attachments/assets/711f23c1-3e7f-4e31-bf90-9d05a491b55b

@BhattAnsh Please review my PR and merge with labels:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@BhattAnsh Please review..???

**Comment by BhattAnsh** [comment]
remove outline and make the background blob more blended

**Comment by harshbhar0629** [comment]
> remove outline and make the background blob more blended

For every input i already set outline-none then which outline you are talking about??

**Comment by harshbhar0629** [comment]
In signup form i used as it is same implementation of login input

**Comment by harshbhar0629** [comment]
Why you don't assign the label.? While merging

**Comment by harshbhar0629** [comment]
@BhattAnsh Please assign the label:)

**Pull request merged**
