### PR TITLE
Google oauth functionality added

### LINKED ISSUE #147: Continue with Google is not working
design-deck vercel app_signup and 7 more pages - Personal 2 - Microsoft​ Edge Beta 11_1_2024 3_20_32 PM

### PR DESCRIPTION
**Pull request by Edasgh**
Fixes : #147 

**Changes**:

**Files created**:
In "QuizQuestFrontend" :
1. "QuizQuestFrontend/src/api/useGoogleOauth.jsx"

In "QuizQuestBackend" :
1.  "QuizQuestBackend/src/middleware/googleAuth.ts"

**Files Modified**:
In "QuizQuestFrontend" :
1. "QuizQuestFrontend/src/App.jsx"
2.  "QuizQuestFrontend/src/pages/Login.jsx"
3.  "QuizQuestFrontend/src/pages/Signup.jsx"

In "QuizQuestBackend" :
1.  "QuizQuestBackend/src/controllers/auth.controller.ts"
2.  "QuizQuestBackend/src/routes/userHandling/register.route.ts"
3.  "QuizQuestBackend/env.md"

**Changes I made**:
In frontend :
1.  Defined a "useGoogleOauth" hook for login with google in the file "useGoogleOauth.jsx",
2.  Imported the "useGoogleOauth" hook and the method "googleLoginSignup" and converted "div" to "button" to add that method as an onClick handler both in "Login.jsx" & "Signup.jsx",
3. In "App.jsx", wrapped the components "Login.jsx" & "Signup.jsx" in "GoogleOauthProvider" to access the google oauth functionality

**Add the env variables : VITE_BACKEND_URL , VITE_GOOGLE_CLIENT_ID, VITE_GOOGLE_CLIENT_SECRET in frontend, else it will show errors**

In backend : 
1.  Added a middleware "googleLogin" for google login in the file "googleAuth.ts",
4.  Defined a controller "loginWithGoogle" for login with google in the file "auth.controller.ts" (`if the user doesn't exist then it will create a new user with the same username, email, so I added a dummy password here for now cause it's a required key`)   ,
5.  Defined a route "/google" (get request) for login with google in the file "register.route.ts",
6. Added necessary env variables in the file "env.md"

**Demo**:
https://www.loom.com/share/0fa057e2fd284bf1a17aca462b1b68b0?sid=bbb46201-3d64-46df-a1fd-96129566d7d4

### CODE REVIEW

**Comment by ShashwatAgrawal20** [comment]
hey @Edasgh the PA will review your PR soon, please wait some time.

**Comment by BhattAnsh** [comment]
great work @Edasgh but from next time when you change any code just write the comment in 3-4 lines for major changes and also add details in readme. If adding any functionality

**Comment by Edasgh** [comment]
> great work @Edasgh but from next time when you change any code just write the comment in 3-4 lines for major changes and also add details in readme. If adding any functionality 
> 

Ok I'll keep that in mind...

**Comment by Edasgh** [comment]
@BhattAnsh please add the gssoc-ext label and a relevant level label here

**Pull request merged**
