### PR TITLE
Added Error404 Page

### PR DESCRIPTION
**Pull request by Dyfintie**
Added Error404 page , and also added the path that shows the error page to the user when they try to connect to an undefined path.
image

### CODE REVIEW

**Comment by BhattAnsh** [comment]
edit in terms of quiz quest it is a quiz platform

**Comment by Dyfintie** [comment]
Ok sir

**Comment by BhattAnsh** [comment]
there is a conflict in your PR can you please check the App.jsx file and fix it

**Comment by Dyfintie** [comment]
> there is a conflict in your PR can you please check the App.jsx file and fix it

Revolved the conflict ✅ Now it can be merged

**Comment by Dyfintie** [comment]
Sir you forgot to give the Gssoc-ext and Hacktoberfest-accepted label to my PR.

**Pull request merged**
