### PR TITLE
Bug: Overflow hidden in x-direction

### LINKED ISSUE #122: BUG: Overflow X-Direction
# 🚀 QuizQuest Issue Tracker

### 🐞 Bug Report

**Title**: BUG: Overflow X-Direction

**Description**: Website home page overflow in x-direction.
- **Steps to Reproduce**:
  1. Edit the width of top level component

- **Expected Result**: No overflow x-direction
- **Actual Result**: Home page overflow in x-direction
- **Screenshots**: 
  

https://github.com/user-attachments/assets/0b7367f5-7eb4-49f8-bd1d-8e9644d1d68d

**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #122 Hide overflow in x-direction

https://github.com/user-attachments/assets/7f47aed2-e54b-4d40-986d-69aa1d91a45f

@BhattAnsh Please assign and review and merge it with labels:)

### CODE REVIEW

**Comment by Wahid7852** [comment]
You were not assigned in the issue first! Refrain from opening a PR unless you get assigned.
@BhattAnsh do you like his PR and would you like to continue with this? or else should i close the issue and the PR

**Comment by BhattAnsh** [comment]
@Wahid7852 i will merge this pr because it was a issue but still @harshbhar0629 from next time don't raise pr when you are not assigned for any issues.

**Comment by harshbhar0629** [comment]
@BhattAnsh please assign level

**Comment by techy4shri** [comment]
@BhattAnsh some points I would like to clear:
1. No contributor is to raise a PR without being assinged. This is the rule.
2. The issue is still there, so this PR didn't solve anything.
3. Just because a PR is raised, you do not have to merge it.

Please check the website once and confirm.

**Comment by harshbhar0629** [comment]
> @BhattAnsh some points I would like to clear:
> 
> 1. No contributor is to raise a PR without being assinged. This is the rule.
> 2. The issue is still there, so this PR didn't solve anything.
> 3. Just because a PR is raised, you do not have to merge it.
> 
> Please check the website once and confirm.

Website deploy from main branch but @BhattAnsh said i have to raised this pr from development branch i have already provide a screenshot

**Comment by harshbhar0629** [comment]
> @BhattAnsh some points I would like to clear:
> 
> 1. No contributor is to raise a PR without being assinged. This is the rule.
> 2. The issue is still there, so this PR didn't solve anything.
> 3. Just because a PR is raised, you do not have to merge it.
> 
> Please check the website once and confirm.

You can see in video there is no overflow in x-direction but when i raised this issue at that time i also provide a video of overflow please check it out

**Comment by harshbhar0629** [comment]
@BhattAnsh @techy4shri  Please assign level:)

**Pull request merged**
