### PR TITLE
Bug: Adding Password View Icon

### LINKED ISSUE #141: BUG: No Password view icon in forms
# 🚀 QuizQuest Issue Tracker

**Title**: [Short description of the bug]

**Description**: There is no password view icon in signup and login form.
- **Steps to Reproduce**:
  1. Add view icon and also add conditional rendering.
- **Expected Result**: User can view our password so that he knows what he is trying to enter and what he/she enter.
- **Actual Result**: Nobody can view our password.
- **Screenshots**: 

login

  
**Environment**:
- **Operating System**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Firefox, Safari)
- **Version**: (e.g., QuizQuest v1.0)

@BhattAnsh Please assign this issue to me with labels:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #141 Adding password view icon.

https://github.com/user-attachments/assets/b910cc2b-2ecf-4d80-bad0-12754bebc949

@BhattAnsh Please review it and merge it:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20  @techy4shri Please review it and merge it:)

**Comment by harshbhar0629** [comment]
@techy4shri Why you don't merge it..???

**Comment by techy4shri** [comment]
@harshbhar0629 you made a PR yesterday, learn to wait a bit. We are humans and cannot be available 24 hours around the clock. The PR will be merged after checks, as soon as we can.

**Comment by harshbhar0629** [comment]
@techy4shri who will merge the PR ?? I mean who is main maintainer of this project??

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20 please review and merge it:)

**Comment by ShashwatAgrawal20** [comment]
@harshbhar0629 will review this tomorrow.

**Comment by harshbhar0629** [comment]
@ShashwatAgrawal20 ok but before 7 pm

**Comment by BhattAnsh** [comment]
there is few conflicts @harshbhar0629

**Comment by harshbhar0629** [comment]
@BhattAnsh @ShashwatAgrawal20 @techy4shri  Please review and merge it:)

**Pull request merged**
